CREATE TABLE IF NOT EXISTS prefectures
(
    id          INT PRIMARY KEY,
    name        VARCHAR(20) NOT NULL,
    area        INT NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS areas
(
    id          INT PRIMARY KEY,
    name        VARCHAR(20) NOT NULL,
    direction   INT NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS directions
(
    id          INT PRIMARY KEY,
    name        VARCHAR(20) NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
