CREATE TABLE IF NOT EXISTS directions
(
    id          INT NOT NULL,
    name        VARCHAR(20) NOT NULL,
    parent_id   INT DEFAULT 0,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS areas
(
    id          INT NOT NULL,
    name        VARCHAR(20) NOT NULL,
    parent_id   INT NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK__area__parent_id FOREIGN KEY (parent_id) REFERENCES directions (id)
);

CREATE TABLE IF NOT EXISTS prefectures
(
    id          INT NOT NULL,
    name        VARCHAR(20) NOT NULL,
    parent_id   INT NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK__prefecture__parent_id FOREIGN KEY (parent_id) REFERENCES areas (id)
);
